# Generated by Django 5.1.7 on 2025-07-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto Fijo'), ('2x1', '2x1'), ('3x2', '3x2')], max_length=20)),
                ('descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje o monto de descuento', max_digits=5)),
                ('categorias', models.CharField(blank=True, help_text='Categorías aplicables (separadas por coma)', max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/')),
                ('activa', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(blank=True, related_name='promociones', to='Inventario.producto')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
